this["JST"] = this["JST"] || {};

this["JST"]["templates/footer.handlebars"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "<footer>\r\n    <div class=\"container\">\r\n        <div class=\"row\">\r\n          <div class=\"col-md-4 footer-leftcol\">\r\n            <p><span class=\"bold-16p\">AOD New York</span><br>\r\n            2250 Lexington Avenue<br>\r\n            Seattle, WA 10035 - <a href=\"#\">warsame@domain.com</a>\r\n            </p>\r\n          </div>\r\n          <div class=\"col-md-4 footer-midcol\">\r\n            <ul>\r\n              <li><a href=\"#\" class=\"twitter-icon\">Twitter</a></li>\r\n              <li><a href=\"#\" class=\"facebook-icon\">Facebook</a></li>\r\n              <li><a href=\"#\" class=\"pintrest-icon\">Pintrest</a></li>\r\n            </ul>\r\n            <div class=\"clearfix\"></div>\r\n          </div>\r\n          <div class=\"col-md-4 footer-rightcol\">\r\n            <p>Bixin <a href=\"#\">Software</a></p>\r\n          </div>\r\n        </div>\r\n      </div>\r\n  </footer>";
},"useData":true});

this["JST"]["templates/head.handlebars"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "\r\n<meta charset=\"utf-8\">\r\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1\">\r\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n  <!-- Bootstrap -->\r\n  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n  <link href=\"http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n  <link rel=\"stylesheet\" href=\"css/flexslider.css?v=1.2\" type=\"text/css\">\r\n  <link rel=\"stylesheet\" href=\"css/style.css\" />\r\n  <link rel=\"stylesheet\" href=\"css/mediaQueries.css\" />\r\n  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css\" rel=\"stylesheet\">\r\n  <!-- Fonts -->\r\n  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>\r\n  <!--favicon-->\r\n  <link rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\">";
},"useData":true});

this["JST"]["templates/navigation.handlebars"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "<div class=\"container-fluid\">\r\n          <div class=\"row\">\r\n            <div class=\"col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2\">\r\n              <nav class=\"pull\">\r\n                <ul class=\"top-nav\">\r\n                  <li><a href=\"index.html\">Home <span class=\"indicator\"><i class=\"fa fa-angle-right\"></i></span></a></li>\r\n                  <li><a href=\"about.html\">About <span class=\"indicator\"><i class=\"fa fa-angle-right\"></i></span></a></li>\r\n                  <li><a href=\"samples.html\">Samples <span class=\"indicator\"><i class=\"fa fa-angle-right\"></i></span></a></li>\r\n                  <li class=\"nav-last\"><a href=\"#contact\">Contact <span class=\"indicator\"><i class=\"fa fa-angle-right\"></i></span></a></li>\r\n                </ul>\r\n              </nav>\r\n            </div>\r\n          </div>\r\n</div>";
},"useData":true});

this["JST"]["templates/scripts.handlebars"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "";
},"useData":true});