this["JST"] = this["JST"] || {};

this["JST"]["templates/footer.handlebars"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "<footer>\n    <div class=\"container\">\n        <div class=\"row\">\n          <div class=\"col-md-4 footer-leftcol\">\n            <p><span class=\"bold-16p\">AOD New York</span><br>\n            2250 Lexington Avenue<br>\n            Seattle, WA 10035 - <a href=\"#\">warsame@domain.com</a>\n            </p>\n          </div>\n          <div class=\"col-md-4 footer-midcol\">\n            <ul>\n              <li><a href=\"#\" class=\"twitter-icon\">Twitter</a></li>\n              <li><a href=\"#\" class=\"facebook-icon\">Facebook</a></li>\n              <li><a href=\"#\" class=\"pintrest-icon\">Pintrest</a></li>\n            </ul>\n            <div class=\"clearfix\"></div>\n          </div>\n          <div class=\"col-md-4 footer-rightcol\">\n            <p>Bixin <a href=\"#\">Software</a></p>\n          </div>\n        </div>\n      </div>\n  </footer>";
},"useData":true});

this["JST"]["templates/head.handlebars"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "\n<meta charset=\"utf-8\">\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1\">\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n  <!-- Bootstrap -->\n  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css\" rel=\"stylesheet\">\n  <link href=\"http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n  <link rel=\"stylesheet\" href=\"css/flexslider.css?v=1.2\" type=\"text/css\">\n  <link rel=\"stylesheet\" href=\"css/style.css\" />\n  <link rel=\"stylesheet\" href=\"css/mediaQueries.css\" />\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.notifyBar.css\" />\n  \n  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css\" rel=\"stylesheet\">\n  <!-- Fonts -->\n  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>\n  <!--favicon-->\n  <link rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\">";
},"useData":true});

this["JST"]["templates/navigation.handlebars"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "<div class=\"container-fluid\">\n          <div class=\"row\">\n            <div class=\"col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2\">\n              <nav class=\"pull\">\n                <ul class=\"top-nav\">\n                  <li><a href=\"index.html\">Home <span class=\"indicator\"><i class=\"fa fa-angle-right\"></i></span></a></li>\n                  <li><a href=\"about.html\">About <span class=\"indicator\"><i class=\"fa fa-angle-right\"></i></span></a></li>\n                  <li><a href=\"samples.html\">Samples <span class=\"indicator\"><i class=\"fa fa-angle-right\"></i></span></a></li>\n                  <li class=\"nav-last\"><a href=\"#contact\">Contact <span class=\"indicator\"><i class=\"fa fa-angle-right\"></i></span></a></li>\n                </ul>\n              </nav>\n            </div>\n          </div>\n</div>";
},"useData":true});

this["JST"]["templates/scripts.handlebars"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "";
},"useData":true});